name: tolab_fci
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  redux: ^5.0.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  flutter_redux: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Launcher Icon
  flutter_launcher_icons: ^0.13.1

  # Splash Screen
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    

# =========================
# LAUNCHER ICON CONFIG
# =========================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/iconapp.png"

# =========================
# SPLASH SCREEN CONFIG
# =========================
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/iconapp.png

  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/icons/iconapp.png
    icon_background_color: "#FFFFFF"

# =========================
# INTERNATIONALIZATION
# =========================
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  class_name: S
  main_locale: en
  preferred_supported_locales:
    - en
    - ar
  nullable_getter: false
  use_deferred_loading: false
  synthetic_package: false
  use_build_runner: true
  overwrite: true
  header: "// GENERATED CODE - DO NOT MODIFY BY HAND\n// ignore_for_file: type=lint"
  examples: false
  sort_arbs_by_key: false
  remove_unused_resources: true
  keep_placeholders: false
  format_code: true
  use_single_quotes: false
  indent: 2
  line_length: 80
